models:
    image: tp33/django
    container_name: models
    external_links:
        - mysql:db
    volumes:
        - ./:/app
    ports:
        - "8001:8000"
    command: >
        bash -c "pip install djangorestframework
        && pip install markdown
        && pip install django-filter
        && python manage.py migrate
        && python manage.py loaddata db.json
        && mod_wsgi-express start-server --working-directory /app/ --reload-on-changes isa-app/wsgi.py"

exp:
    image: tp33/django
    container_name: exp
    links:
        - models:models-api
        - es:es
        - kafka:kafka
    ports:
        - "8002:8000"
    volumes:
        - ../experience-layer:/app
    command: "mod_wsgi-express start-server --reload-on-changes experience-layer/wsgi.py"

web_1:
    image: tp33/django
    container_name: web_1
    links:
        - exp:exp-api
    ports:
        - "8004:8000"
    volumes:
        - ../front-layer:/app
    command: "mod_wsgi-express start-server --reload-on-changes front-layer/wsgi.py"

web_2:
    image: tp33/django
    container_name: web_2
    links:
        - exp:exp-api
    volumes:
        - ../front-layer:/app
    command: "mod_wsgi-express start-server --reload-on-changes front-layer/wsgi.py"

haproxy:
    build: images/haproxy
    container_name: haproxy
    links:
        - web_1:web_1
        - web_2:web_2
    ports:
        - "80:80"
    volumes:
        - ../isa-app:/app

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - es:es
      - kafka:kafka
   volumes:
      - ../isa-app:/app
   command: python3 batchScript.py

selenium-chrome:
  image: selenium/standalone-chrome
  container_name: selenium-chrome
  links:
    - web_1:web
  ports:
    - "4444:4444"

selenium-test:
  image: tp33/django
  container_name: selenium-test
  links:
    - selenium-chrome:selenium-chrome
    - web_1:web
  volumes:
    - ../isa-app:/app
  command: bash -c "pip install selenium==3.14.0 && python integration.py"

spark-master:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
  container_name: spark-master
  hostname: spark-master
  environment:
    MASTER: spark://spark-master:7077
    SPARK_CONF_DIR: /conf
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./data:/tmp/data

spark-worker:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  container_name: spark-worker
  hostname: spark-worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 512m
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - spark-master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./data:/tmp/data

spark-batch:
  image: tp33/django
  container_name: spark-batch
  links:
     - kafka:kafka
  volumes:
     - ../isa-app:/app
  command: bash -c "rm ./data/access.log && python3 spark-batch.py"
